
package me.devsaki.hentoid.database.domains;

import io.objectbox.BoxStore;
import io.objectbox.BoxStoreBuilder;
import io.objectbox.ModelBuilder;
import io.objectbox.ModelBuilder.EntityBuilder;
import io.objectbox.model.PropertyFlags;
import io.objectbox.model.PropertyType;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.
/**
 * Starting point for working with your ObjectBox. All boxes are set up for your objects here.
 * <p>
 * First steps (Android): get a builder using {@link #builder()}, call {@link BoxStoreBuilder#androidContext(Object)},
 * and {@link BoxStoreBuilder#build()} to get a {@link BoxStore} to work with.
 */
public class MyObjectBox {

    public static BoxStoreBuilder builder() {
        BoxStoreBuilder builder = new BoxStoreBuilder(getModel());
        builder.entity(Attribute_.__INSTANCE);
        builder.entity(AttributeLocation_.__INSTANCE);
        builder.entity(Chapter_.__INSTANCE);
        builder.entity(Content_.__INSTANCE);
        builder.entity(DuplicateEntry_.__INSTANCE);
        builder.entity(ErrorRecord_.__INSTANCE);
        builder.entity(Group_.__INSTANCE);
        builder.entity(GroupItem_.__INSTANCE);
        builder.entity(ImageFile_.__INSTANCE);
        builder.entity(QueueRecord_.__INSTANCE);
        builder.entity(SearchRecord_.__INSTANCE);
        builder.entity(ShuffleRecord_.__INSTANCE);
        builder.entity(SiteBookmark_.__INSTANCE);
        builder.entity(SiteHistory_.__INSTANCE);
        return builder;
    }

    private static byte[] getModel() {
        ModelBuilder modelBuilder = new ModelBuilder();
        modelBuilder.lastEntityId(16, 6863432510804694130L);
        modelBuilder.lastIndexId(23, 4823016725405687888L);
        modelBuilder.lastRelationId(3, 1412032361666532056L);

        buildEntityAttribute(modelBuilder);
        buildEntityAttributeLocation(modelBuilder);
        buildEntityChapter(modelBuilder);
        buildEntityContent(modelBuilder);
        buildEntityDuplicateEntry(modelBuilder);
        buildEntityErrorRecord(modelBuilder);
        buildEntityGroup(modelBuilder);
        buildEntityGroupItem(modelBuilder);
        buildEntityImageFile(modelBuilder);
        buildEntityQueueRecord(modelBuilder);
        buildEntitySearchRecord(modelBuilder);
        buildEntityShuffleRecord(modelBuilder);
        buildEntitySiteBookmark(modelBuilder);
        buildEntitySiteHistory(modelBuilder);

        return modelBuilder.build();
    }

    private static void buildEntityAttribute(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("Attribute");
        entityBuilder.id(1, 6281760634329431587L).lastPropertyId(6, 2675592496735450076L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 5108740755096578000L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("name", PropertyType.String).id(3, 6218026218593161392L)
                .flags(PropertyFlags.INDEX_HASH).indexId(6, 3376665178160538616L);
        entityBuilder.property("type", PropertyType.Int).id(4, 9136188553462176700L)
                .flags(PropertyFlags.NON_PRIMITIVE_TYPE | PropertyFlags.INDEXED).indexId(7, 689427048355118025L);
        entityBuilder.property("groupId", "Group", "group", PropertyType.Relation).id(6, 2675592496735450076L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(13, 7082707691451462644L);


        entityBuilder.entityDone();
    }

    private static void buildEntityAttributeLocation(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("AttributeLocation");
        entityBuilder.id(7, 4254529074075444756L).lastPropertyId(4, 4617716480765519668L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 7498338443352299457L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("site", PropertyType.Long).id(2, 4100011129763730697L)
                .flags(PropertyFlags.NON_PRIMITIVE_TYPE);
        entityBuilder.property("url", PropertyType.String).id(3, 1589781357027616630L);
        entityBuilder.property("attributeId", "Attribute", "attribute", PropertyType.Relation).id(4, 4617716480765519668L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(8, 5756463807096430367L);


        entityBuilder.entityDone();
    }

    private static void buildEntityChapter(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("Chapter");
        entityBuilder.id(14, 4653544552059492176L).lastPropertyId(7, 8254213446255957923L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 4156971629848544062L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("order", PropertyType.Int).id(2, 426074786695752558L)
                .flags(PropertyFlags.NON_PRIMITIVE_TYPE);
        entityBuilder.property("url", PropertyType.String).id(3, 502849545006987713L);
        entityBuilder.property("name", PropertyType.String).id(4, 8970541480018695522L);
        entityBuilder.property("uniqueId", PropertyType.String).id(6, 2875790170342417054L);
        entityBuilder.property("uploadDate", PropertyType.Long).id(7, 8254213446255957923L);
        entityBuilder.property("contentId", "Content", "content", PropertyType.Relation).id(5, 8187979340827089166L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(18, 7973014573351069918L);


        entityBuilder.entityDone();
    }

    private static void buildEntityContent(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("Content");
        entityBuilder.id(2, 5880334030341287801L).lastPropertyId(31, 4486721253337313651L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 1481988948624328056L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("url", PropertyType.String).id(2, 5800889076602216395L)
                .flags(PropertyFlags.INDEX_HASH).indexId(14, 601529990271626923L);
        entityBuilder.property("uniqueSiteId", PropertyType.String).id(15, 7783986187434244415L);
        entityBuilder.property("title", PropertyType.String).id(3, 1869970397575581249L);
        entityBuilder.property("author", PropertyType.String).id(4, 2417271458982667075L);
        entityBuilder.property("coverImageUrl", PropertyType.String).id(5, 674677213140156811L);
        entityBuilder.property("qtyPages", PropertyType.Int).id(6, 7062308019963509495L)
                .flags(PropertyFlags.NON_PRIMITIVE_TYPE);
        entityBuilder.property("uploadDate", PropertyType.Long).id(7, 7301578355206155477L);
        entityBuilder.property("downloadDate", PropertyType.Long).id(8, 1827842303404521643L);
        entityBuilder.property("downloadCompletionDate", PropertyType.Long).id(29, 6098325687122950518L);
        entityBuilder.property("status", PropertyType.Int).id(9, 2429762886376715363L)
                .flags(PropertyFlags.NON_PRIMITIVE_TYPE | PropertyFlags.INDEXED).indexId(15, 1566418967334516190L);
        entityBuilder.property("site", PropertyType.Long).id(10, 5174313231174202310L)
                .flags(PropertyFlags.NON_PRIMITIVE_TYPE | PropertyFlags.INDEXED).indexId(16, 2424237144553088526L);
        entityBuilder.property("storageFolder", PropertyType.String).id(11, 6249972361468615650L);
        entityBuilder.property("storageUri", PropertyType.String).id(21, 2083354954158879943L);
        entityBuilder.property("favourite", PropertyType.Bool).id(12, 3838124773804113972L);
        entityBuilder.property("rating", PropertyType.Int).id(31, 4486721253337313651L);
        entityBuilder.property("completed", PropertyType.Bool).id(26, 72694651852852193L);
        entityBuilder.property("reads", PropertyType.Long).id(13, 4211894395290313595L);
        entityBuilder.property("lastReadDate", PropertyType.Long).id(14, 4722516447694741314L);
        entityBuilder.property("lastReadPageIndex", PropertyType.Int).id(17, 903347587815260256L);
        entityBuilder.property("manuallyMerged", PropertyType.Bool).id(28, 576356326453963220L);
        entityBuilder.property("bookPreferences", PropertyType.String).id(22, 100030316656175582L)
                .flags(PropertyFlags.NON_PRIMITIVE_TYPE);
        entityBuilder.property("downloadMode", PropertyType.Int).id(27, 993320760546602021L);
        entityBuilder.property("size", PropertyType.Long).id(23, 3011527446686134185L);
        entityBuilder.property("readProgress", PropertyType.Float).id(25, 515620137730542700L);
        entityBuilder.property("downloadParams", PropertyType.String).id(16, 4321603102287256155L);
        entityBuilder.property("isBeingDeleted", PropertyType.Bool).id(18, 9117635469382092615L);
        entityBuilder.property("jsonUri", PropertyType.String).id(19, 326862264253525250L);
        entityBuilder.property("isFlaggedForDeletion", PropertyType.Bool).id(24, 6637631044428919138L);
        entityBuilder.property("contentToReplaceId", "Content", "contentToReplace", PropertyType.Relation).id(30, 5191599344995061842L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(23, 4823016725405687888L);

        entityBuilder.relation("attributes", 1, 4430709372206389603L, 1, 6281760634329431587L);

        entityBuilder.entityDone();
    }

    private static void buildEntityDuplicateEntry(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("DuplicateEntry");
        entityBuilder.id(13, 7937878460553138785L).lastPropertyId(10, 4636705001081237914L);

        entityBuilder.property("referenceId", PropertyType.Long).id(8, 7706865596199564791L);
        entityBuilder.property("referenceSize", PropertyType.Long).id(7, 1098218792851277018L);
        entityBuilder.property("duplicateId", PropertyType.Long).id(9, 1179341344641812936L);
        entityBuilder.property("duplicateSize", PropertyType.Long).id(10, 4636705001081237914L);
        entityBuilder.property("titleScore", PropertyType.Float).id(3, 2093692672368655834L);
        entityBuilder.property("coverScore", PropertyType.Float).id(4, 1857179527185107957L);
        entityBuilder.property("artistScore", PropertyType.Float).id(5, 334967191803969001L);
        entityBuilder.property("id", PropertyType.Long).id(6, 4769062372712151805L)
                .flags(PropertyFlags.ID);


        entityBuilder.entityDone();
    }

    private static void buildEntityErrorRecord(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("ErrorRecord");
        entityBuilder.id(8, 2761588808510077107L).lastPropertyId(7, 4722768682213725119L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 5654464950513562356L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("type", PropertyType.Int).id(2, 97618489394466159L)
                .flags(PropertyFlags.NON_PRIMITIVE_TYPE);
        entityBuilder.property("url", PropertyType.String).id(3, 5266874309167836641L);
        entityBuilder.property("contentPart", PropertyType.String).id(4, 2374260660208047890L);
        entityBuilder.property("description", PropertyType.String).id(5, 5938637064174550118L);
        entityBuilder.property("timestamp", PropertyType.Long).id(7, 4722768682213725119L)
                .flags(PropertyFlags.NON_PRIMITIVE_TYPE);
        entityBuilder.property("contentId", "Content", "content", PropertyType.Relation).id(6, 6859233072010087049L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(9, 6133215885572986701L);


        entityBuilder.entityDone();
    }

    private static void buildEntityGroup(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("Group");
        entityBuilder.id(10, 5605025377139576552L).lastPropertyId(15, 1348329171224080512L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 4942308531039589914L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("grouping", PropertyType.Int).id(2, 7314675986286179953L)
                .flags(PropertyFlags.NON_PRIMITIVE_TYPE | PropertyFlags.INDEXED).indexId(20, 5101223626385692255L);
        entityBuilder.property("name", PropertyType.String).id(3, 3253833421051356444L);
        entityBuilder.property("subtype", PropertyType.Int).id(12, 1853611665269246534L);
        entityBuilder.property("order", PropertyType.Int).id(4, 7301610536566936428L);
        entityBuilder.property("hasCustomBookOrder", PropertyType.Bool).id(8, 3893141455284576703L);
        entityBuilder.property("propertyMin", PropertyType.Int).id(10, 9048723417612746722L);
        entityBuilder.property("propertyMax", PropertyType.Int).id(11, 979612020950126568L);
        entityBuilder.property("favourite", PropertyType.Bool).id(13, 1008829494719594190L);
        entityBuilder.property("rating", PropertyType.Int).id(15, 1348329171224080512L);
        entityBuilder.property("isBeingDeleted", PropertyType.Bool).id(6, 1399053985046563297L);
        entityBuilder.property("isFlaggedForDeletion", PropertyType.Bool).id(9, 6155860565053663303L);
        entityBuilder.property("coverContentId", "Content", "coverContent", PropertyType.Relation).id(14, 8168924561252314098L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(21, 2677634342952249814L);


        entityBuilder.entityDone();
    }

    private static void buildEntityGroupItem(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("GroupItem");
        entityBuilder.id(11, 8625892909159295220L).lastPropertyId(4, 9123943307733808224L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 3934422964416291812L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("order", PropertyType.Int).id(2, 166930667547828018L);
        entityBuilder.property("contentId", "Content", "content", PropertyType.Relation).id(3, 3316566234858855188L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(11, 5074100101684896469L);
        entityBuilder.property("groupId", "Group", "group", PropertyType.Relation).id(4, 9123943307733808224L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(12, 7789399647013237776L);


        entityBuilder.entityDone();
    }

    private static void buildEntityImageFile(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("ImageFile");
        entityBuilder.id(3, 2849837771881495731L).lastPropertyId(17, 4756936261641767706L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 3113966914893868320L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("order", PropertyType.Int).id(2, 4786164809804019689L)
                .flags(PropertyFlags.NON_PRIMITIVE_TYPE);
        entityBuilder.property("url", PropertyType.String).id(3, 8847017078500757224L);
        entityBuilder.property("pageUrl", PropertyType.String).id(17, 4756936261641767706L);
        entityBuilder.property("name", PropertyType.String).id(4, 8890585972764734377L);
        entityBuilder.property("fileUri", PropertyType.String).id(11, 2035492345579360157L);
        entityBuilder.property("read", PropertyType.Bool).id(14, 2962440896788849680L);
        entityBuilder.property("favourite", PropertyType.Bool).id(9, 3938664550318760597L);
        entityBuilder.property("isCover", PropertyType.Bool).id(12, 946562145146984364L);
        entityBuilder.property("status", PropertyType.Int).id(5, 7613843228223628057L)
                .flags(PropertyFlags.NON_PRIMITIVE_TYPE);
        entityBuilder.property("mimeType", PropertyType.String).id(10, 5317663031556875099L);
        entityBuilder.property("size", PropertyType.Long).id(13, 7859042547729264819L);
        entityBuilder.property("imageHash", PropertyType.Long).id(15, 5135092662762413378L);
        entityBuilder.property("downloadParams", PropertyType.String).id(7, 8627441942081468691L);
        entityBuilder.property("contentId", "Content", "content", PropertyType.Relation).id(6, 6745828261307358394L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(4, 7771600038559568217L);
        entityBuilder.property("chapterId", "Chapter", "chapter", PropertyType.Relation).id(16, 5043947488067507192L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(17, 525280893618987138L);


        entityBuilder.entityDone();
    }

    private static void buildEntityQueueRecord(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("QueueRecord");
        entityBuilder.id(4, 3086874109297661629L).lastPropertyId(4, 1209356155950397260L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 2024523736113657395L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("rank", PropertyType.Int).id(2, 1320640807096340636L);
        entityBuilder.property("contentId", "Content", "content", PropertyType.Relation).id(3, 5421570333026902379L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(3, 6276640449349847797L);


        entityBuilder.entityDone();
    }

    private static void buildEntitySearchRecord(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("SearchRecord");
        entityBuilder.id(16, 6863432510804694130L).lastPropertyId(4, 6744868481394814636L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 2721505157584142575L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("searchString", PropertyType.String).id(2, 3497865025886606869L);
        entityBuilder.property("label", PropertyType.String).id(4, 6744868481394814636L);


        entityBuilder.entityDone();
    }

    private static void buildEntityShuffleRecord(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("ShuffleRecord");
        entityBuilder.id(15, 2260398621202196035L).lastPropertyId(2, 5934700032431888672L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 6481436522626559668L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("contentId", PropertyType.Long).id(2, 5934700032431888672L)
                .flags(PropertyFlags.NON_PRIMITIVE_TYPE);


        entityBuilder.entityDone();
    }

    private static void buildEntitySiteBookmark(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("SiteBookmark");
        entityBuilder.id(12, 6339833598022566662L).lastPropertyId(6, 5135118656468009739L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 5961866071036702599L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("site", PropertyType.Long).id(2, 4349006808582983106L)
                .flags(PropertyFlags.NON_PRIMITIVE_TYPE);
        entityBuilder.property("title", PropertyType.String).id(5, 1710077713562043737L);
        entityBuilder.property("url", PropertyType.String).id(3, 1801728411621493048L);
        entityBuilder.property("order", PropertyType.Int).id(4, 3231983556416278030L);
        entityBuilder.property("isHomepage", PropertyType.Bool).id(6, 5135118656468009739L);


        entityBuilder.entityDone();
    }

    private static void buildEntitySiteHistory(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("SiteHistory");
        entityBuilder.id(9, 2854716855695893043L).lastPropertyId(3, 4569323833343490328L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 3959853759284796367L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("site", PropertyType.Long).id(2, 2830371251693076427L)
                .flags(PropertyFlags.NON_PRIMITIVE_TYPE);
        entityBuilder.property("url", PropertyType.String).id(3, 4569323833343490328L);


        entityBuilder.entityDone();
    }


}
